try:
    print(x)

except:
    print("An Error Occurred")

finally:
    print("Successful")